<%@ Page Title="" Language="C#" MasterPageFile="~/admin/MasterPage.master" AutoEventWireup="true" CodeFile="deleteproduct.aspx.cs" Inherits="admin_deleteproduct" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<div id="page-wrapper">
    <div id="page-inner">
        <div>
            <h2>Plz provide any detail of the product that you wish to delete from database.</h2>
            <asp:TextBox ID="pro_id" placeholder="product id" runat="server"></asp:TextBox><br /><b>or</b><br />
            <asp:TextBox ID="pro_name" placeholder="product name" runat="server"></asp:TextBox><br /><br />
            <asp:Button ID="Button1" runat="server" Text="delete" onclick="Button1_Click" />
        </div>
        &nbsp;
        <div>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True">
            </asp:GridView>
            
        </div>
    </div><!-- /. PAGE INNER  -->
</div><!-- /. PAGE WRAPPER  -->        
</asp:Content>

